### ISSUE TITLE
[Bug] Does not support transparent textures.

### ISSUE THREAD

**Issue by Lomeli12** [Thog92/ISBRH#1]
I have been trying to implement connected textured glass, however, it appears transparent textures are not supported. Any transparent space filled black, as shown:

![Black Fill](https://d1zqrvc06emslq.cloudfront.net/media/originals/feedpost/86/17/ed/f8bac30ecd93e506c2f719a3bbf3a9f4.jpg)

Since what I'm doing for connected textures is overlay the textures, this obviously causes a bit of a problem.

RenderHandler: http://paste.ubuntu.com/10675434/
ConnectedTexture: http://paste.ubuntu.com/10675446/
BlockClass: http://paste.ubuntu.com/10675450/

**Comment by marysaka** [comment]
You have made a mistake!
If you want to render transparent texture, It's not TRANSLUCENT but CUTOUT in getBlockLayer().

![BlockRenderLayers](http://1.bp.blogspot.com/-_-OS_TXprLI/VJse0vd0yEI/AAAAAAAAAS4/N-amHvloPFs/s1600/141222RvW-BlockRenderLayers.png)

Thanks for reporting anyway

Source: BlockGlass and http://greyminecraftcoder.blogspot.com.au/2014/12/block-rendering-18.html

**Comment by Lomeli12** [comment]
Setting it to either CUTOUT or CUTOUT_MIPPED just stops it from rendering all together.

![What?](http://i.imgur.com/cwOTAWf.png)

**Comment by marysaka** [comment]
That is strange, why is that rendering correctly in your inventory? That should work... What is your texture size?

EDIT: I think that is not a problem with the mod actually but from you implementation of renderStandardBlockWithColorMultiplier

**Comment by Lomeli12** [comment]
So, I found this interesting little thing. If have it set to CUTOUT_MIPPED, it can't render unless near a Grass block or leaf block. Tested it with both my BlockRenderer and the SimpleBlockRender.
![2015-03-26_15 32 06](https://cloud.githubusercontent.com/assets/637246/6858713/73692278-d3ce-11e4-8a85-56ed0656a4dc.png)
![2015-03-26_15 32 09](https://cloud.githubusercontent.com/assets/637246/6858715/7369ef8c-d3ce-11e4-811e-a40e5190ac70.png)
![2015-03-26_15 38 05](https://cloud.githubusercontent.com/assets/637246/6858712/736810b8-d3ce-11e4-840f-6ddbbc7d3945.png)
![2015-03-26_15 38 07](https://cloud.githubusercontent.com/assets/637246/6858714/736979bc-d3ce-11e4-9194-2acc95e2d451.png)

Edit: The example tables also do not render after a certain Y-Level.
![2015-03-26_15 45 39](https://cloud.githubusercontent.com/assets/637246/6858824/3e6f5bea-d3cf-11e4-8cf0-c84251fd0cb0.png)

**Comment by marysaka** [comment]
This is weird, I will try to reproduce this bug today

**Comment by marysaka** [comment]
Oups...

So I have made some test. The problem seem to append when y >= 80 and if you don't have a vanilla block of the same layer (I have tried with modded regular block). It seem to be a problem of Forge (I already have got that problem in 1.6.4 and 1.7.10). I will continue investigation tomorrow.

**Comment by marysaka** [comment]
Ok so after a lots of test it's seem that the ASM hook is bugged
